# Temp control with python

In [1]:
import serial
import time
import datetime as dt

convert pythons datetime to the matlab format

open the serial port

Listen for input and print it into a textfile

Close the serial and the socket port

In [ ]:
import socket
import sys
import time
import serial
import datetime as dt
import numpy as np
import h5py

HOST = ''   # Symbolic name meaning all available interfaces
PORT = 8899 # Arbitrary non-privileged port
 

try:
    ser = serial.Serial('COM32', 9600, timeout = 1)
except serial.SerialException:
    s.close()
    ser.close()
    ser = serial.Serial('COM32', 9600, timeout = 1)

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
print 'Socket created'

try:
    s.bind((HOST, PORT))
except socket.error , msg:
    print 'Bind failed. Error Code : ' + str(msg[0]) + ' Message ' + msg[1]
    sys.exit()
     
print 'Socket bind complete'

s.listen(5)
print 'Socket now listening'


    
    
print 'Serial COM32 is now listening'
while True:
    #wait to accept a connection - blocking call
    conn, addr = s.accept()
 
    #display client information
    print 'Connected with ' + addr[0] + ':' + str(addr[1])

    #now get stuff from the client
    data = conn.recv(1024)
    reply = 'OK...' + data
    
    ser.flushInput();
    line = ser.readline();
    ard_str = line.decode(encoding='windows-1252');
    try:
        vals = np.array(ard_str.split(','), dtype =float)    
        fname = 'N:\\' + data[3:]
        time.sleep(5)
        f = h5py.File(fname, "a")
        params = f['globals']
        params.attrs['T_Verr'] = vals[0]
        params.attrs['T_Vmeas'] = vals[1]
        params.attrs['T_Vinp'] = vals[2]
        f.close()
        print vals
        print reply
    except (ValueError, IndexError) as e:
        print 'Convert failed for string: ' + ard_str
        

    # if data is zero this means that the connection was lost and we can actually close our server
    if not data: 
        break
    conn.sendall(reply)
    time.sleep(0.2)
    conn.close()

Socket created
Socket bind complete
Socket now listening
Serial COM32 is now listening
Connected with 129.206.181.217:62351
[  -1.  701.    0.]
OK...E:\Labordaten\2017-09\2017-09-25\hdf5_data\run022.h5
Connected with 129.206.181.217:62358
[   1.9         698.1          19.39624405]
OK...E:\Labordaten\2017-09\2017-09-25\hdf5_data\run023.h5
Connected with 129.206.181.217:62363
[   3.1        696.9         32.7297554]
OK...E:\Labordaten\2017-09\2017-09-25\hdf5_data\run024.h5
Connected with 129.206.181.217:62370
Convert failed for string: 1778793334

Connected with 129.206.181.217:62376
[  -3.  703.    0.]
OK...E:\Labordaten\2017-09\2017-09-25\hdf5_data\run026.h5
Connected with 129.206.181.217:62382
[  -2.4  702.4    0. ]
OK...E:\Labordaten\2017-09\2017-09-25\hdf5_data\run027.h5
Connected with 129.206.181.217:62401
[   0.         700.           2.2370007]
OK...E:\Labordaten\2017-09\2017-09-25\hdf5_data\run028.h5
Connected with 129.206.181.217:62408
[   3.5         696.5          40.4040031

In [4]:
s.close()
ser.close()

NameError: name 's' is not defined